/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ida..Faber (https://sketchfab.com/Ida..Faber)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/shiba-inu-dog-80419f7e64e24afe97e0931b6aeee612
title: Shiba Inu Dog
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./shiba_inu_dog/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 4.05, 0]}>
            <mesh geometry={nodes.polySurface1_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface2_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface3_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface4_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface5_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface6_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface7_lambert1_0.geometry} material={materials.lambert1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./shiba_inu_dog/scene.gltf')
